$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  units:
    type: string

  ref:
    type: object
    properties:
      index:
        type: string
      annotation:
        type: string
    required:
      - index
      - annotation


  params:
    type: object
    properties:
      star: 
        type: string
    required:
      - star

required:
  - units
  - ref
  - params
